#include "JuceBridge.h"

#ifndef JUCE_DEBUG
 // BinaryData.h is generated by juce_add_binary_data(SubtreactionalWebUI …)
 // and only exists when the Release build includes that target.
 #include "BinaryData.h"
#endif

//==============================================================================
static juce::WebBrowserComponent::Options makeBrowserOptions()
{
    juce::WebBrowserComponent::Options opts;
   #if JUCE_WINDOWS
    // Default Windows backend is IE (ES5 only) — request WebView2 (Chromium/Edge).
    // Requires JUCE_USE_WIN_WEBVIEW2=1 and WebView2LoaderStatic.lib at link time.
    opts = opts.withBackend (juce::WebBrowserComponent::Options::Backend::webview2);

    auto wv2 = juce::WebBrowserComponent::Options::WinWebView2()
                   .withUserDataFolder (
                       juce::File::getSpecialLocation (juce::File::userApplicationDataDirectory)
                           .getChildFile ("Subtreactional"))
                   .withBackgroundColour (juce::Colour (0xff121212));

    opts = opts.withWinWebView2Options (wv2);
   #endif
    return opts;
}

static juce::String makeNumericArrayLiteral (const float* values, int numValues)
{
    juce::String s;
    s.preallocateBytes (numValues * 10);
    s << "[";

    for (int i = 0; i < numValues; ++i)
    {
        if (i != 0)
            s << ",";
        s << juce::String (values[i], 6);
    }

    s << "]";
    return s;
}

JuceBridge::JuceBridge (SubtreactionalAudioProcessor& p)
    : WebBrowserComponent (makeBrowserOptions()), processor (p)
{
    // Page load is deferred to parentHierarchyChanged() so that WKWebView
    // always has a real window when it starts rendering.  Loading here
    // (before addAndMakeVisible) causes WKWebView to initialise without a
    // window, which makes some hosts (e.g. Bitwig) show a blank screen.
}

void JuceBridge::loadInitialPage()
{
#if JUCE_DEBUG
    goToURL ("http://localhost:5173");
#else
    auto tmp = juce::File::getSpecialLocation (juce::File::tempDirectory)
                   .getChildFile ("subtreactional_ui.html");
    tmp.replaceWithData (BinaryData::index_html, BinaryData::index_htmlSize);
    goToURL (juce::URL (tmp).toString (false));
#endif
}

void JuceBridge::parentHierarchyChanged()
{
    WebBrowserComponent::parentHierarchyChanged();

    // Load the page the first time the component is in a showing window.
    // isShowing() is true only when the component has a peer and is visible —
    // i.e. WKWebView will have a real NSWindow to render into.
    if (! pageLoadStarted_ && isShowing())
    {
        pageLoadStarted_ = true;
        loadInitialPage();
    }
}

//==============================================================================
void JuceBridge::pushParam (const juce::String& id, float value)
{
    // JUCE 7 has no evaluateJavascript() public method, but goToURL("javascript:...")
    // is specially handled by the WKWebViewImpl backend: it calls
    // [WKWebView evaluateJavaScript:completionHandler:nil] directly (see
    // juce_WebBrowserComponent_mac.mm WKWebViewImpl::goToURL lines ~539-545).
    goToURL ("javascript:window.__juce && window.__juce.onParam("
             + id.quoted() + "," + juce::String (value, 6) + ")");
}

void JuceBridge::pushWaveform (const float* points, int numPoints)
{
    if (points == nullptr || numPoints <= 0)
        return;

    goToURL ("javascript:window.__juce && window.__juce.onWaveform("
             + makeNumericArrayLiteral (points, numPoints) + ")");
}

void JuceBridge::pushCPU (float loadProportion)
{
    goToURL ("javascript:window.__juce && window.__juce.onCPU(" + juce::String (loadProportion, 4) + ")");
}

void JuceBridge::pushLFOValues (const float* vals, int n)
{
    if (vals == nullptr || n <= 0)
        return;

    goToURL ("javascript:window.__juce && window.__juce.onLFO("
             + makeNumericArrayLiteral (vals, n) + ")");
}

void JuceBridge::pushSpectrogram (const float* bins, int numBins)
{
    if (bins == nullptr || numBins <= 0)
        return;

    goToURL ("javascript:window.__juce && window.__juce.onSpectrogram("
             + makeNumericArrayLiteral (bins, numBins) + ")");
}

void JuceBridge::pushAllParams()
{
    goToURL ("javascript:window.__juce && window.__juce.onVersion("
             + juce::String (JucePlugin_VersionString).quoted() + ")");

    for (int i = 0; i < SubtreactionalAudioProcessor::kNumParams; ++i)
    {
        const auto& p = SubtreactionalAudioProcessor::kParams[i];
        // getValue() returns the normalised 0..1 value, matching what the JS
        // side expects (it converts back to display range on its end).
        if (auto* param = processor.apvts.getParameter (p.apvtsId))
            pushParam (p.apvtsId, param->getValue());
    }

    // play_mode is excluded from kParams[] to avoid triggering st_synth_panic()
    // on every audio block, so push it explicitly here.
    if (auto* param = processor.apvts.getParameter ("play_mode"))
        pushParam ("play_mode", param->getValue());

    pushModAssignments();
    pushPresetList();
}

void JuceBridge::pushPresetList()
{
    const auto list = processor.getPresetList();

    juce::String json = "[";
    bool first = true;
    for (const auto& p : list)
    {
        if (! first) json << ",";
        first = false;

        auto esc = [] (const juce::String& s) -> juce::String
        {
            return s.replace ("\\", "\\\\")
                    .replace ("\"", "\\\"")
                    .replace ("\n", "\\n")
                    .replace ("\r", "");
        };

        json << "{"
             << "\"name\":"        << esc(p.name).quoted()        << ","
             << "\"author\":"      << esc(p.author).quoted()      << ","
             << "\"description\":" << esc(p.description).quoted() << ","
             << "\"pack\":"        << esc(p.pack).quoted()        << ","
             << "\"category\":"    << esc(p.category).quoted()    << ","
             << "\"source\":\""    << (p.isFactory ? "factory" : "user") << "\",";

        if (p.isFactory)
            json << "\"idx\":" << p.factoryIdx;
        else
            json << "\"path\":" << esc(p.filePath).quoted();

        json << "}";
    }
    json << "]";

    goToURL ("javascript:window.__juce && window.__juce.onPresets(" + json + ")");
}

void JuceBridge::pushModAssignments()
{
    const auto& assignments = processor.getModAssignments();

    juce::String json = "[";
    bool first = true;
    for (const auto& a : assignments)
    {
        if (! first) json << ",";
        first = false;
        const char* typeStr = a.sourceType == 0 ? "lfo"
                            : a.sourceType == 1 ? "macro"
                            : a.sourceType == 2 ? "key" : "vel";
        json << "{"
             << "\"type\":\"" << typeStr << "\","
             << "\"idx\":"    << a.sourceIdx << ","
             << "\"param\":"  << a.paramName.quoted() << ","
             << "\"depth\":"  << juce::String (a.depth, 4)
             << "}";
    }
    json << "]";

    goToURL ("javascript:window.__juce && window.__juce.onModAssignments(" + json + ")");
}

//==============================================================================
bool JuceBridge::pageAboutToLoad (const juce::String& newURL)
{
    // Intercept  juce://ready  and send current state once JS has fully booted.
    if (newURL.startsWith ("juce://ready"))
    {
        pushAllParams();
        return false; // cancel navigation
    }

    // Intercept  juce://param?id=<id>&v=<value>
    if (newURL.startsWith ("juce://param"))
    {
        // Parse query string manually (no external URL library needed)
        juce::String query = newURL.fromFirstOccurrenceOf ("?", false, false);

        juce::String id;
        float value = 0.0f;

        for (auto& token : juce::StringArray::fromTokens (query, "&", ""))
        {
            auto key = token.upToFirstOccurrenceOf ("=", false, false);
            auto val = token.fromFirstOccurrenceOf ("=", false, false);

            if (key == "id")
                id = juce::URL::removeEscapeChars (val);
            else if (key == "v")
                value = val.getFloatValue();
        }

        if (id.isNotEmpty())
        {
            if (auto* param = processor.apvts.getParameter (id))
                param->setValueNotifyingHost (value);
        }

        return false; // cancel navigation
    }

    // Intercept  juce://mod_add?src=<lfo|macro>&idx=<n>&param=<name>&depth=<d>
    if (newURL.startsWith ("juce://mod_add") || newURL.startsWith ("juce://mod_remove")
        || newURL.startsWith ("juce://mod_depth"))
    {
        juce::String query = newURL.fromFirstOccurrenceOf ("?", false, false);

        juce::String src, paramName;
        int idx = 0;
        float depth = 0.5f;

        for (auto& token : juce::StringArray::fromTokens (query, "&", ""))
        {
            auto key = token.upToFirstOccurrenceOf ("=", false, false);
            auto val = token.fromFirstOccurrenceOf ("=", false, false);

            if (key == "src")
                src = val;
            else if (key == "idx")
                idx = val.getIntValue();
            else if (key == "param")
                paramName = juce::URL::removeEscapeChars (val);
            else if (key == "depth")
                depth = val.getFloatValue();
        }

        // source_type: 0 = LFO, 1 = Macro, 2 = Key, 3 = Vel
        const int sourceType = (src == "macro") ? 1
                             : (src == "key")   ? 2
                             : (src == "vel")   ? 3 : 0;

        if (newURL.startsWith ("juce://mod_add"))
            processor.modAdd (sourceType, idx, paramName, depth);
        else if (newURL.startsWith ("juce://mod_remove"))
            processor.modRemove (sourceType, idx, paramName);
        else
            processor.modSetDepth (sourceType, idx, paramName, depth);

        return false; // cancel navigation
    }

    // juce://preset_load_factory?idx=N
    if (newURL.startsWith ("juce://preset_load_factory"))
    {
        juce::String query = newURL.fromFirstOccurrenceOf ("?", false, false);
        int idx = -1;
        for (auto& token : juce::StringArray::fromTokens (query, "&", ""))
        {
            auto key = token.upToFirstOccurrenceOf ("=", false, false);
            auto val = token.fromFirstOccurrenceOf ("=", false, false);
            if (key == "idx") idx = val.getIntValue();
        }
        const int capturedIdx = idx;
        juce::MessageManager::callAsync ([this, capturedIdx]() {
            processor.loadFactoryPreset (capturedIdx);
            pushAllParams();   // pushes params + mod assignments + preset list
        });
        return false;
    }

    // juce://preset_load_user?path=<url-encoded-path>
    if (newURL.startsWith ("juce://preset_load_user"))
    {
        juce::String query = newURL.fromFirstOccurrenceOf ("?", false, false);
        juce::String path;
        for (auto& token : juce::StringArray::fromTokens (query, "&", ""))
        {
            auto key = token.upToFirstOccurrenceOf ("=", false, false);
            auto val = token.fromFirstOccurrenceOf ("=", false, false);
            if (key == "path") path = juce::URL::removeEscapeChars (val);
        }
        juce::MessageManager::callAsync ([this, path]() {
            processor.loadUserPreset (path);
            pushAllParams();   // pushes params + mod assignments + preset list
        });
        return false;
    }

    // juce://native_save_dialog?name=<url-encoded-name>
    // Shows a native JUCE AlertWindow so typing doesn't trigger DAW shortcuts.
    if (newURL.startsWith ("juce://native_save_dialog"))
    {
        juce::String name, pack, category;
        for (auto& token : juce::StringArray::fromTokens (
                               newURL.fromFirstOccurrenceOf ("?", false, false), "&", ""))
        {
            auto key = token.upToFirstOccurrenceOf ("=", false, false);
            auto val = juce::URL::removeEscapeChars (token.fromFirstOccurrenceOf ("=", false, false));
            if      (key == "name")     name     = val;
            else if (key == "pack")     pack     = val;
            else if (key == "category") category = val;
        }

        juce::MessageManager::callAsync ([this, name, pack, category]()
        {
            auto* dialog = new juce::AlertWindow ("Save Preset", "", juce::MessageBoxIconType::NoIcon);
            dialog->setLookAndFeel (&darkLAF);
            dialog->addTextEditor ("name",   name,     "Name:");
            dialog->addTextEditor ("author", "",       "Author:");
            dialog->addTextEditor ("desc",   "",       "Description:");
            dialog->addTextEditor ("pack",   pack,     "Pack:");
            dialog->addTextEditor ("cat",    category, "Category:");
            dialog->addButton ("Save",   1, juce::KeyPress (juce::KeyPress::returnKey));
            dialog->addButton ("Cancel", 0, juce::KeyPress (juce::KeyPress::escapeKey));

            dialog->enterModalState (true,
                juce::ModalCallbackFunction::create ([this, dialog] (int result)
                {
                    if (result == 1)
                    {
                        auto pk = dialog->getTextEditorContents ("pack").trim();
                        auto ct = dialog->getTextEditorContents ("cat").trim();
                        auto n  = dialog->getTextEditorContents ("name").trim();
                        if (n.isEmpty()) n = "Untitled";
                        processor.saveUserPreset (pk, ct, n,
                            dialog->getTextEditorContents ("author").trim(),
                            dialog->getTextEditorContents ("desc").trim());
                        pushPresetList();
                        goToURL ("javascript:window.__juce && window.__juce.onPresetSaved("
                                 + n.quoted() + ","
                                 + pk.quoted() + ","
                                 + ct.quoted() + ")");
                    }
                    dialog->setLookAndFeel (nullptr);
                }), true);
        });
        return false;
    }

    // juce://preset_save?name=...&author=...&desc=...
    if (newURL.startsWith ("juce://preset_save"))
    {
        juce::String query = newURL.fromFirstOccurrenceOf ("?", false, false);
        juce::String name, author, desc;
        for (auto& token : juce::StringArray::fromTokens (query, "&", ""))
        {
            auto key = token.upToFirstOccurrenceOf ("=", false, false);
            auto val = juce::URL::removeEscapeChars (token.fromFirstOccurrenceOf ("=", false, false));
            if      (key == "name")   name   = val;
            else if (key == "author") author = val;
            else if (key == "desc")   desc   = val;
        }
        juce::MessageManager::callAsync ([this, name, author, desc]() {
            processor.saveUserPreset ({}, {}, name, author, desc);
            pushPresetList();
        });
        return false;
    }

    return true; // allow all other navigations
}

void JuceBridge::pageFinishedLoading (const juce::String& /*url*/)
{
    pushAllParams();

    if (onPageReady)
        onPageReady();
}
