#include "JuceBridge.h"

#ifndef JUCE_DEBUG
 // BinaryData.h is generated by juce_add_binary_data(SubtreactionalWebUI …)
 // and only exists when the Release build includes that target.
 #include "BinaryData.h"
#endif

//==============================================================================
static juce::WebBrowserComponent::Options makeBrowserOptions()
{
    juce::WebBrowserComponent::Options opts;
   #if JUCE_WINDOWS
    // Default Windows backend is IE (ES5 only) — request WebView2 (Chromium/Edge).
    // JUCE silently falls back to IE if WebView2 runtime is not installed,
    // so ship with the WebView2 bootstrapper or document the runtime requirement.
    opts = opts.withBackend (juce::WebBrowserComponent::Options::Backend::webview2);
   #endif
    return opts;
}

JuceBridge::JuceBridge (SubtreactionalAudioProcessor& p)
    : WebBrowserComponent (makeBrowserOptions()), processor (p)
{
#if JUCE_DEBUG
    goToURL ("http://localhost:5173");
#else
    // Write the embedded HTML to a temp file and load it via file://
    // juce::File has no getURL(); construct juce::URL from the File instead.
    auto tmp = juce::File::getSpecialLocation (juce::File::tempDirectory)
                   .getChildFile ("subtreactional_ui.html");
    tmp.replaceWithData (BinaryData::index_html, BinaryData::index_htmlSize);
    goToURL (juce::URL (tmp).toString (false));
#endif
}

//==============================================================================
void JuceBridge::pushParam (const juce::String& id, float value)
{
    // JUCE 7 has no evaluateJavascript() public method, but goToURL("javascript:...")
    // is specially handled by the WKWebViewImpl backend: it calls
    // [WKWebView evaluateJavaScript:completionHandler:nil] directly (see
    // juce_WebBrowserComponent_mac.mm WKWebViewImpl::goToURL lines ~539-545).
    goToURL ("javascript:window.__juce && window.__juce.onParam("
             + id.quoted() + "," + juce::String (value, 6) + ")");
}

void JuceBridge::pushAllParams()
{
    for (int i = 0; i < SubtreactionalAudioProcessor::kNumParams; ++i)
    {
        const auto& p = SubtreactionalAudioProcessor::kParams[i];
        // getValue() returns the normalised 0..1 value, matching what the JS
        // side expects (it converts back to display range on its end).
        if (auto* param = processor.apvts.getParameter (p.apvtsId))
            pushParam (p.apvtsId, param->getValue());
    }
}

//==============================================================================
bool JuceBridge::pageAboutToLoad (const juce::String& newURL)
{
    // Intercept  juce://param?id=<id>&v=<value>
    if (newURL.startsWith ("juce://param"))
    {
        // Parse query string manually (no external URL library needed)
        juce::String query = newURL.fromFirstOccurrenceOf ("?", false, false);

        juce::String id;
        float value = 0.0f;

        for (auto& token : juce::StringArray::fromTokens (query, "&", ""))
        {
            auto key = token.upToFirstOccurrenceOf ("=", false, false);
            auto val = token.fromFirstOccurrenceOf ("=", false, false);

            if (key == "id")
                id = juce::URL::removeEscapeChars (val);
            else if (key == "v")
                value = val.getFloatValue();
        }

        if (id.isNotEmpty())
        {
            if (auto* param = processor.apvts.getParameter (id))
                param->setValueNotifyingHost (value);
        }

        return false; // cancel navigation
    }

    return true; // allow all other navigations
}

void JuceBridge::pageFinishedLoading (const juce::String& /*url*/)
{
    pushAllParams();
}
